/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 720069
 */
public class finalexam extends javax.swing.JFrame {
     private int level = 1;
    int Score = 0;
    String name = "any";
    /**
     * Creates new form finalexam
     */
    public finalexam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Click = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leader = new javax.swing.JTextArea();
        namebox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Click1 = new javax.swing.JButton();
        Click3 = new javax.swing.JButton();
        Click8 = new javax.swing.JButton();
        Click10 = new javax.swing.JButton();
        Click11 = new javax.swing.JButton();
        Click13 = new javax.swing.JButton();
        Click16 = new javax.swing.JButton();
        Click17 = new javax.swing.JButton();
        Click18 = new javax.swing.JButton();
        Click19 = new javax.swing.JButton();
        Click20 = new javax.swing.JButton();
        Click21 = new javax.swing.JButton();
        Click22 = new javax.swing.JButton();
        Click23 = new javax.swing.JButton();
        Click24 = new javax.swing.JButton();
        Click25 = new javax.swing.JButton();
        Click26 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Click.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click.setForeground(new java.awt.Color(255, 0, 0));
        Click.setText("Click");
        Click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Cookie Smasher");
        jLabel1.setOpaque(true);

        leader.setColumns(20);
        leader.setRows(5);
        jScrollPane1.setViewportView(leader);

        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Name Here:");

        Click1.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click1.setForeground(new java.awt.Color(255, 0, 0));
        Click1.setText("Click");
        Click1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click1ActionPerformed(evt);
            }
        });

        Click3.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click3.setForeground(new java.awt.Color(255, 0, 0));
        Click3.setText("Click");
        Click3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click3ActionPerformed(evt);
            }
        });

        Click8.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click8.setForeground(new java.awt.Color(255, 0, 0));
        Click8.setText("Click");
        Click8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click8ActionPerformed(evt);
            }
        });

        Click10.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click10.setForeground(new java.awt.Color(255, 0, 0));
        Click10.setText("Click");
        Click10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click10ActionPerformed(evt);
            }
        });

        Click11.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click11.setForeground(new java.awt.Color(255, 0, 0));
        Click11.setText("Click");
        Click11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click11ActionPerformed(evt);
            }
        });

        Click13.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click13.setForeground(new java.awt.Color(255, 0, 0));
        Click13.setText("Click");
        Click13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click13ActionPerformed(evt);
            }
        });

        Click16.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click16.setForeground(new java.awt.Color(255, 0, 0));
        Click16.setText("Click");
        Click16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click16ActionPerformed(evt);
            }
        });

        Click17.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click17.setForeground(new java.awt.Color(255, 0, 0));
        Click17.setText("Click");
        Click17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click17ActionPerformed(evt);
            }
        });

        Click18.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click18.setForeground(new java.awt.Color(255, 0, 0));
        Click18.setText("Click");
        Click18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click18ActionPerformed(evt);
            }
        });

        Click19.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click19.setForeground(new java.awt.Color(255, 0, 0));
        Click19.setText("Click");
        Click19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click19ActionPerformed(evt);
            }
        });

        Click20.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click20.setForeground(new java.awt.Color(255, 0, 0));
        Click20.setText("Click");
        Click20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click20ActionPerformed(evt);
            }
        });

        Click21.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click21.setForeground(new java.awt.Color(255, 0, 0));
        Click21.setText("Click");
        Click21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click21ActionPerformed(evt);
            }
        });

        Click22.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click22.setForeground(new java.awt.Color(255, 0, 0));
        Click22.setText("Click");
        Click22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click22ActionPerformed(evt);
            }
        });

        Click23.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click23.setForeground(new java.awt.Color(255, 0, 0));
        Click23.setText("Click");
        Click23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click23ActionPerformed(evt);
            }
        });

        Click24.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click24.setForeground(new java.awt.Color(255, 0, 0));
        Click24.setText("Click");
        Click24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click24ActionPerformed(evt);
            }
        });

        Click25.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click25.setForeground(new java.awt.Color(255, 0, 0));
        Click25.setText("Click");
        Click25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click25ActionPerformed(evt);
            }
        });

        Click26.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        Click26.setForeground(new java.awt.Color(255, 0, 0));
        Click26.setText("Click");
        Click26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Click26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namebox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Click13, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Click8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Click11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Click, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Click22, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Click16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Click3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Click23, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Click18, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Click17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Click26, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Click25, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Click24, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Click1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Click20, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Click10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Click21, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Click19, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Click)
                    .addComponent(Click22)
                    .addComponent(Click16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Click11)
                    .addComponent(Click13)
                    .addComponent(Click8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Click3)
                            .addComponent(Click23))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Click18)
                            .addComponent(Click17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Click10)
                            .addComponent(Click21)
                            .addComponent(Click19))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Click1)
                            .addComponent(Click20)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Click25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Click26)
                                .addGap(9, 9, 9)
                                .addComponent(Click24))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickActionPerformed
         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 1;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
      
    }//GEN-LAST:event_ClickActionPerformed

    private void Click1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click1ActionPerformed
                 level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 2;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
      
    }//GEN-LAST:event_Click1ActionPerformed

    private void Click3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click3ActionPerformed
                 level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 3;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
      
    }//GEN-LAST:event_Click3ActionPerformed

    private void Click8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click8ActionPerformed
                        level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 4;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click8ActionPerformed

    private void Click10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click10ActionPerformed
                        level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 5;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click10ActionPerformed

    private void Click11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click11ActionPerformed
                         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 6;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click11ActionPerformed

    private void Click13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click13ActionPerformed
                       level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 7;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click13ActionPerformed

    private void Click16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click16ActionPerformed
                         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 8;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click16ActionPerformed

    private void Click17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click17ActionPerformed
                         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 9;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click17ActionPerformed

    private void Click18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click18ActionPerformed
                         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 10;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click18ActionPerformed

    private void Click19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click19ActionPerformed
                         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 11;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click19ActionPerformed

    private void Click20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click20ActionPerformed
                        level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 12;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click20ActionPerformed

    private void Click21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click21ActionPerformed
                         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 13;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click21ActionPerformed

    private void Click22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click22ActionPerformed
                         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 14;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click22ActionPerformed

    private void Click23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click23ActionPerformed
                        level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 15;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click23ActionPerformed

    private void Click24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click24ActionPerformed
                         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 16;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click24ActionPerformed

    private void Click25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click25ActionPerformed
                         level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 17;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click25ActionPerformed

    private void Click26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Click26ActionPerformed
                        level ++; 
         name = namebox.getText();
         
         for(int i = 0;i < level ;i++){
             Score += 18;
               leader.setText(  name + " : " + Score + " Cookies ");
         }
    }//GEN-LAST:event_Click26ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finalexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finalexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finalexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finalexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalexam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Click;
    private javax.swing.JButton Click1;
    private javax.swing.JButton Click10;
    private javax.swing.JButton Click11;
    private javax.swing.JButton Click13;
    private javax.swing.JButton Click16;
    private javax.swing.JButton Click17;
    private javax.swing.JButton Click18;
    private javax.swing.JButton Click19;
    private javax.swing.JButton Click20;
    private javax.swing.JButton Click21;
    private javax.swing.JButton Click22;
    private javax.swing.JButton Click23;
    private javax.swing.JButton Click24;
    private javax.swing.JButton Click25;
    private javax.swing.JButton Click26;
    private javax.swing.JButton Click3;
    private javax.swing.JButton Click8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea leader;
    private javax.swing.JTextField namebox;
    // End of variables declaration//GEN-END:variables
}
